# Generated by Django 5.1.5 on 2025-09-02 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_assigned_to'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
