# Generated by Django 5.1.5 on 2025-09-02 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_taskdetail_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdetail',
            name='asset',
            field=models.ImageField(blank=True, default='task_asset/default_img.jpg', null=True, upload_to='task_asset'),
        ),
    ]
